baseURL = "https://blog.aaronbieber.com/"
languageCode = "en-us"
title = "The Chronicle"
theme = "chronicle"
uglyURLs = true
enableEmoji = true

[services.rss]
  limit = 10

[params]
  disqusShortName = "aaronbieber"
  author = "abieber"
  subtitle = "of a ColdFusion Expatriate"
  bio = "Hi, I'm Aaron Bieber. Once, long ago, I wrote ColdFusion for a living. Now I coach engineering leaders and write about tech and social topics on this blog."
  recentPosts = 5

[permalinks]
  posts = "/:year/:month/:day/:slug"

[markup]
  [markup.highlight]
    style = "friendly"